### ISSUE TITLE
USER STORY: <Site Navigation>

### ISSUE THREAD

**Issue by moirahartigan** [moirahartigan/the-lady-goldsmith#1]
As an **unregistered user** I want to **see that the navigation bar is displayed with a logo on all pages** with a search box, My account, Wishlist and shopping bag icons on a desktop device

**Comment by moirahartigan** [comment]
# Acceptance Criteria:
* the navigation bar is displayed on all pages with a search box, My account, Wishlist and shopping bag icons on a mobile/tablet device

# Tasks:
- [] Add logo
- [] Add nav bar
- [] Add navbar links
- [] Add category links
- [ ] Create dropdown for options
