### ISSUE TITLE
USER STORY: Search products

### ISSUE THREAD

**Issue by moirahartigan** [moirahartigan/the-lady-goldsmith#11]
As a **Shopper** I want to be able to **use the search option** so I can **search the site for specific keywords**

# Acceptance Criteria:
* search box will be visible on all pages
* users can search by keyword/ product / category

# Tasks:
- [ ] add search box
- [ ] filter by category
- [ ] filter by rating
