### ISSUE TITLE
USER STORY: Browse Products

### ISSUE THREAD

**Issue by moirahartigan** [moirahartigan/the-lady-goldsmith#2]
As an **unregistered** I want to **browse through all available products** without being logged in.

**Comment by moirahartigan** [comment]
# Acceptance Criteria:
* Any site user can browse and view products
* The site user does not have to register an account in order to view products
* The site user does not have to log in to view a product
* The site user will be able to scroll through a collection of products on the landing page

# Tasks:
- [ ] Make products available on the landing page 
- [ ] Create a product card view
- [ ] test the functionality
